# modules/monitoring/values.yaml

# [1] Grafana (시각화 대시보드)
grafana:
  enabled: true
  adminPassword: "" # main.tf에서 SSM 파라미터 값으로 동적 주입됩니다!
  defaultDashboardsTimezone: Asia/Seoul
  service:
    type: ClusterIP
  persistence:
    enabled: false

# [2] Prometheus (메트릭 수집기)
prometheus:
  prometheusSpec:
    retention: 1d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 200m
        memory: 512Mi

# [3] Alertmanager (알람 발송 컴포넌트)
alertmanager:
  enabled: true
  persistence:
    enabled: false
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['namespace', 'alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'slack-notifications'
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - api_url: "" # main.tf에서 SSM 파라미터 값으로 동적 주입됩니다!
        channel: '#team3-alerts' # 실제 알람을 받을 슬랙 채널명으로 맞춰주세요
        send_resolved: true

# [4] 기타 인프라 모니터링 도구
kubeStateMetrics:
  enabled: true

# 불필요한 EKS 기본 경고 규칙 정리
defaultRules:
  create: true
  rules:
    kubeProxy: false